require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');

const productsData = [
  // Nike
  {
    name: 'Nike Revolution 6',
    brand: 'Nike',
    category: 'Footwear',
    gender: 'Men',
    mrp: 6500,
    price: 4499,
    discount: 30,
    description: 'Lightweight and comfortable running shoes',
    colors: ['Black', 'White', 'Blue'],
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400', 'https://images.unsplash.com/photo-1488882691919-a455a6153456?w=400'],
    stock: 50,
    rating: 4.5,
    reviews: 120,
  },
  {
    name: 'Nike Dri-FIT T-Shirt',
    brand: 'Nike',
    category: 'Topwear',
    gender: 'Men',
    mrp: 2500,
    price: 1599,
    discount: 36,
    description: 'Breathable moisture-wicking T-shirt',
    colors: ['Black', 'White', 'Red', 'Blue'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400'],
    stock: 100,
    rating: 4.3,
    reviews: 245,
  },
  {
    name: 'Nike Flex Shorts',
    brand: 'Nike',
    category: 'Bottomwear',
    gender: 'Men',
    mrp: 2200,
    price: 1399,
    discount: 36,
    description: 'Lightweight and flexible shorts',
    colors: ['Black', 'Grey', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: ['https://images.unsplash.com/photo-1506268307895-0b2e8b4b5f59?w=400'],
    stock: 75,
    rating: 4.2,
    reviews: 98,
  },
  {
    name: 'Nike Running Tank Top',
    brand: 'Nike',
    category: 'Topwear',
    gender: 'Women',
    mrp: 2300,
    price: 1449,
    discount: 37,
    description: 'Sleeveless tank top for women',
    colors: ['Pink', 'Purple', 'Black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://images.unsplash.com/photo-1506259987452-6006e1ce8995?w=400'],
    stock: 60,
    rating: 4.4,
    reviews: 167,
  },
  {
    name: 'Nike Kids Sportswear',
    brand: 'Nike',
    category: 'Topwear',
    gender: 'Kids',
    mrp: 1800,
    price: 999,
    discount: 44,
    description: 'Comfortable sportswear for kids',
    colors: ['Blue', 'Red', 'Yellow'],
    sizes: ['2XS', 'XS', 'S', 'M'],
    images: ['https://images.unsplash.com/photo-1556821552-5f6abf0c4fa9?w=400'],
    stock: 85,
    rating: 4.5,
    reviews: 134,
  },

  // Adidas
  {
    name: 'Adidas Ultraboost 21',
    brand: 'Adidas',
    category: 'Footwear',
    gender: 'Men',
    mrp: 20000,
    price: 13999,
    discount: 30,
    description: 'Premium running shoes with boost technology',
    colors: ['Black', 'White', 'Grey'],
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400'],
    stock: 40,
    rating: 4.6,
    reviews: 289,
  },
  {
    name: 'Adidas Essentials T-Shirt',
    brand: 'Adidas',
    category: 'Topwear',
    gender: 'Men',
    mrp: 2000,
    price: 1199,
    discount: 40,
    description: 'Classic essentials T-shirt',
    colors: ['Black', 'White', 'Blue', 'Green'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400'],
    stock: 120,
    rating: 4.2,
    reviews: 312,
  },
  {
    name: 'Adidas Track Pants',
    brand: 'Adidas',
    category: 'Bottomwear',
    gender: 'Men',
    mrp: 3500,
    price: 2099,
    discount: 40,
    description: 'Comfortable track pants',
    colors: ['Black', 'Navy', 'Grey'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: ['https://images.unsplash.com/photo-1506629082847-11d3e392e787?w=400'],
    stock: 90,
    rating: 4.3,
    reviews: 201,
  },
  {
    name: 'Adidas Performance Bra',
    brand: 'Adidas',
    category: 'Topwear',
    gender: 'Women',
    mrp: 2500,
    price: 1599,
    discount: 36,
    description: 'Sports bra for women',
    colors: ['Black', 'Hot Pink', 'Navy'],
    sizes: ['32B', '34B', '36B', '38B'],
    images: ['https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=400'],
    stock: 70,
    rating: 4.4,
    reviews: 178,
  },
  {
    name: 'Adidas Kids Jacket',
    brand: 'Adidas',
    category: 'Topwear',
    gender: 'Kids',
    mrp: 3000,
    price: 1799,
    discount: 40,
    description: 'Warm jacket for kids',
    colors: ['Blue', 'Red', 'Black'],
    sizes: ['2XS', 'XS', 'S', 'M', 'L'],
    images: ['https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=400'],
    stock: 65,
    rating: 4.5,
    reviews: 145,
  },

  // Zara
  {
    name: 'Zara Original Fit Jeans',
    brand: 'Zara',
    category: 'Bottomwear',
    gender: 'Men',
    mrp: 4500,
    price: 3299,
    discount: 27,
    description: 'Premium denim jeans',
    colors: ['Dark Blue', 'Light Blue', 'Black'],
    sizes: ['28', '30', '32', '34', '36', '38', '40'],
    images: ['https://images.unsplash.com/photo-1542272604-787c62d465d1?w=400'],
    stock: 100,
    rating: 4.4,
    reviews: 456,
  },
  {
    name: 'Zara Basic Shirt',
    brand: 'Zara',
    category: 'Topwear',
    gender: 'Men',
    mrp: 3500,
    price: 2299,
    discount: 34,
    description: 'Casual and comfortable shirt',
    colors: ['White', 'Blue', 'Black', 'Beige'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: ['https://images.unsplash.com/photo-1596084065118-1d00648ac63d?w=400'],
    stock: 110,
    rating: 4.2,
    reviews: 234,
  },
  {
    name: 'Zara Midi Dress',
    brand: 'Zara',
    category: 'Topwear',
    gender: 'Women',
    mrp: 5500,
    price: 3799,
    discount: 31,
    description: 'Elegant midi dress for women',
    colors: ['Black', 'Red', 'Navy', 'White'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://images.unsplash.com/photo-1572804419140-8f6a3f11c9ff?w=400'],
    stock: 80,
    rating: 4.6,
    reviews: 289,
  },
  {
    name: 'Zara High Waist Trousers',
    brand: 'Zara',
    category: 'Bottomwear',
    gender: 'Women',
    mrp: 4200,
    price: 2799,
    discount: 33,
    description: 'Professional high waist trousers',
    colors: ['Black', 'Grey', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L'],
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400'],
    stock: 75,
    rating: 4.3,
    reviews: 167,
  },
  {
    name: 'Zara Kids Sweater',
    brand: 'Zara',
    category: 'Topwear',
    gender: 'Kids',
    mrp: 2000,
    price: 1299,
    discount: 35,
    description: 'Soft and warm sweater',
    colors: ['Grey', 'Navy', 'Brown'],
    sizes: ['2XS', 'XS', 'S', 'M'],
    images: ['https://images.unsplash.com/photo-1578932750294-708xdbfdb3c0?w=400'],
    stock: 95,
    rating: 4.4,
    reviews: 123,
  },

  // H&M
  {
    name: 'H&M Casual T-Shirt',
    brand: 'H&M',
    category: 'Topwear',
    gender: 'Men',
    mrp: 1500,
    price: 799,
    discount: 47,
    description: 'Basic casual T-shirt',
    colors: ['Black', 'White', 'Grey', 'Blue'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: ['https://images.unsplash.com/photo-1501196354995-cdcc315a3340?w=400'],
    stock: 200,
    rating: 4.1,
    reviews: 501,
  },
  {
    name: 'H&M Chino Pants',
    brand: 'H&M',
    category: 'Bottomwear',
    gender: 'Men',
    mrp: 2500,
    price: 1499,
    discount: 40,
    description: 'Comfortable chino pants',
    colors: ['Khaki', 'Navy', 'Black', 'Grey'],
    sizes: ['28', '30', '32', '34', '36', '38'],
    images: ['https://images.unsplash.com/photo-1584918898459-02edbb0eb0e0?w=400'],
    stock: 130,
    rating: 4.2,
    reviews: 278,
  },
  {
    name: 'H&M Maxi Skirt',
    brand: 'H&M',
    category: 'Bottomwear',
    gender: 'Women',
    mrp: 2200,
    price: 1299,
    discount: 41,
    description: 'Flowing maxi skirt',
    colors: ['Black', 'White', 'Floral'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://images.unsplash.com/photo-1606689873959-53fc2e5ae5f0?w=400'],
    stock: 85,
    rating: 4.3,
    reviews: 145,
  },
  {
    name: 'H&M Crop Top',
    brand: 'H&M',
    category: 'Topwear',
    gender: 'Women',
    mrp: 1800,
    price: 999,
    discount: 44,
    description: 'Trendy crop top',
    colors: ['White', 'Black', 'Pink'],
    sizes: ['XS', 'S', 'M', 'L'],
    images: ['https://images.unsplash.com/photo-1502716488279-9a60edc96849?w=400'],
    stock: 110,
    rating: 4.3,
    reviews: 198,
  },
  {
    name: 'H&M Kids T-Shirt',
    brand: 'H&M',
    category: 'Topwear',
    gender: 'Kids',
    mrp: 1000,
    price: 599,
    discount: 40,
    description: 'Colorful kids T-shirt',
    colors: ['Red', 'Blue', 'Yellow', 'Green'],
    sizes: ['2XS', 'XS', 'S', 'M', 'L'],
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400'],
    stock: 180,
    rating: 4.2,
    reviews: 212,
  },

  // FASHIONISTA
  {
    name: 'FASHIONISTA Denim Jacket',
    brand: 'FASHIONISTA',
    category: 'Topwear',
    gender: 'Men',
    mrp: 12000,
    price: 7999,
    discount: 33,
    description: 'Premium denim jacket',
    colors: ['Light Blue', 'Dark Blue', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: ['https://images.unsplash.com/photo-1576995853950-3135dd27f172?w=400'],
    stock: 45,
    rating: 4.7,
    reviews: 176,
  },
  {
    name: 'FASHIONISTA Slim Jeans',
    brand: 'FASHIONISTA',
    category: 'Bottomwear',
    gender: 'Men',
    mrp: 9500,
    price: 5999,
    discount: 37,
    description: 'Slim fit designer jeans',
    colors: ['Dark Blue', 'Black', 'Blue'],
    sizes: ['28', '30', '32', '34', '36', '38'],
    images: ['https://images.unsplash.com/photo-1542272604-787c62d465d1?w=400'],
    stock: 70,
    rating: 4.6,
    reviews: 234,
  },
  {
    name: 'FASHIONISTA Boots',
    brand: 'FASHIONISTA',
    category: 'Footwear',
    gender: 'Men',
    mrp: 15000,
    price: 9999,
    discount: 33,
    description: 'Premium leather boots',
    colors: ['Black', 'Brown'],
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    images: ['https://images.unsplash.com/photo-1543163521-9145f2c742f1?w=400'],
    stock: 35,
    rating: 4.8,
    reviews: 89,
  },
  {
    name: 'FASHIONISTA Leather Jacket',
    brand: 'FASHIONISTA',
    category: 'Topwear',
    gender: 'Women',
    mrp: 18000,
    price: 11999,
    discount: 33,
    description: 'Premium leather jacket for women',
    colors: ['Black', 'Brown'],
    sizes: ['XS', 'S', 'M', 'L'],
    images: ['https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=400'],
    stock: 30,
    rating: 4.7,
    reviews: 112,
  },
  {
    name: 'FASHIONISTA Kids Hoodie',
    brand: 'FASHIONISTA',
    category: 'Topwear',
    gender: 'Kids',
    mrp: 4500,
    price: 2999,
    discount: 33,
    description: 'Premium hoodie for kids',
    colors: ['Black', 'Grey', 'Navy'],
    sizes: ['2XS', 'XS', 'S', 'M', 'L'],
    images: ['https://images.unsplash.com/photo-1556821552-5f6abf0c4fa9?w=400'],
    stock: 55,
    rating: 4.6,
    reviews: 98,
  },

  // Levi's
  {
    name: 'Levis 501 Jeans',
    brand: 'Levi\'s',
    category: 'Bottomwear',
    gender: 'Men',
    mrp: 5500,
    price: 3799,
    discount: 31,
    description: 'Classic Levi\'s 501 jeans',
    colors: ['Blue', 'Black', 'Dark Blue'],
    sizes: ['28', '30', '32', '34', '36', '38', '40'],
    images: ['https://images.unsplash.com/photo-1542272604-787c62d465d1?w=400'],
    stock: 150,
    rating: 4.5,
    reviews: 512,
  },
  {
    name: 'Levis T-Shirt',
    brand: 'Levi\'s',
    category: 'Topwear',
    gender: 'Men',
    mrp: 2000,
    price: 1199,
    discount: 40,
    description: 'Classic Levi\'s T-shirt',
    colors: ['White', 'Black', 'Red'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: ['https://images.unsplash.com/photo-1501196354995-cdcc315a3340?w=400'],
    stock: 180,
    rating: 4.3,
    reviews: 334,
  },
  {
    name: 'Levis Skinny Jeans',
    brand: 'Levi\'s',
    category: 'Bottomwear',
    gender: 'Women',
    mrp: 4500,
    price: 2999,
    discount: 33,
    description: 'Levis skinny jeans for women',
    colors: ['Blue', 'Black', 'Grey'],
    sizes: ['24', '26', '28', '30', '32'],
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400'],
    stock: 120,
    rating: 4.4,
    reviews: 267,
  },
  {
    name: 'Levis Jacket',
    brand: 'Levi\'s',
    category: 'Topwear',
    gender: 'Women',
    mrp: 6500,
    price: 4299,
    discount: 34,
    description: 'Classic denim jacket for women',
    colors: ['Light Blue', 'Dark Blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://images.unsplash.com/photo-1576995853950-3135dd27f172?w=400'],
    stock: 85,
    rating: 4.5,
    reviews: 178,
  },
  {
    name: 'Levis Kids Jeans',
    brand: 'Levi\'s',
    category: 'Bottomwear',
    gender: 'Kids',
    mrp: 2500,
    price: 1599,
    discount: 36,
    description: 'Comfortable jeans for kids',
    colors: ['Blue', 'Black'],
    sizes: ['2XS', 'XS', 'S', 'M', 'L'],
    images: ['https://images.unsplash.com/photo-1506629082847-11d3e392e787?w=400'],
    stock: 140,
    rating: 4.3,
    reviews: 145,
  },

  // Puma
  {
    name: 'Puma Running Shoes',
    brand: 'Puma',
    category: 'Footwear',
    gender: 'Men',
    mrp: 7500,
    price: 4999,
    discount: 33,
    description: 'High performance running shoes',
    colors: ['Black', 'White', 'Red'],
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400'],
    stock: 95,
    rating: 4.4,
    reviews: 201,
  },
  {
    name: 'Puma Aop T-Shirt',
    brand: 'Puma',
    category: 'Topwear',
    gender: 'Men',
    mrp: 2000,
    price: 1199,
    discount: 40,
    description: 'All over print T-shirt',
    colors: ['Black', 'White', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400'],
    stock: 110,
    rating: 4.2,
    reviews: 178,
  },
  {
    name: 'Puma Joggers',
    brand: 'Puma',
    category: 'Bottomwear',
    gender: 'Men',
    mrp: 3500,
    price: 2099,
    discount: 40,
    description: 'Comfortable joggers',
    colors: ['Black', 'Grey', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: ['https://images.unsplash.com/photo-1506269944852-7f4e65fda5b9?w=400'],
    stock: 80,
    rating: 4.3,
    reviews: 134,
  },
  {
    name: 'Puma Sports Leggings',
    brand: 'Puma',
    category: 'Bottomwear',
    gender: 'Women',
    mrp: 3000,
    price: 1799,
    discount: 40,
    description: 'High waisted leggings',
    colors: ['Black', 'Grey', 'Pink'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://images.unsplash.com/photo-1506269944852-7f4e65fda5b9?w=400'],
    stock: 100,
    rating: 4.4,
    reviews: 212,
  },
  {
    name: 'Puma Kids Shoes',
    brand: 'Puma',
    category: 'Footwear',
    gender: 'Kids',
    mrp: 3500,
    price: 2199,
    discount: 37,
    description: 'Fun and comfortable kids shoes',
    colors: ['Red', 'Blue', 'Pink'],
    sizes: ['1', '2', '3', '4', '5', '6'],
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400'],
    stock: 120,
    rating: 4.5,
    reviews: 167,
  },

  // UCB (United Colors of Benetton)
  {
    name: 'UCB Sweater',
    brand: 'UCB',
    category: 'Topwear',
    gender: 'Men',
    mrp: 3500,
    price: 2099,
    discount: 40,
    description: 'Warm wool sweater',
    colors: ['Grey', 'Navy', 'Brown', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: ['https://images.unsplash.com/photo-1578932750294-708xdbfdb3c0?w=400'],
    stock: 65,
    rating: 4.3,
    reviews: 112,
  },
  {
    name: 'UCB Casual Shirt',
    brand: 'UCB',
    category: 'Topwear',
    gender: 'Men',
    mrp: 2800,
    price: 1699,
    discount: 39,
    description: 'Casual button-up shirt',
    colors: ['White', 'Blue', 'Pink'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: ['https://images.unsplash.com/photo-1596084065118-1d00648ac63d?w=400'],
    stock: 90,
    rating: 4.2,
    reviews: 145,
  },
  {
    name: 'UCB Dress Pants',
    brand: 'UCB',
    category: 'Bottomwear',
    gender: 'Men',
    mrp: 3200,
    price: 1999,
    discount: 37,
    description: 'Professional dress pants',
    colors: ['Black', 'Grey', 'Navy', 'Brown'],
    sizes: ['28', '30', '32', '34', '36', '38'],
    images: ['https://images.unsplash.com/photo-1584918898459-02edbb0eb0e0?w=400'],
    stock: 75,
    rating: 4.3,
    reviews: 98,
  },
  {
    name: 'UCB Cotton Dress',
    brand: 'UCB',
    category: 'Topwear',
    gender: 'Women',
    mrp: 4500,
    price: 2699,
    discount: 40,
    description: 'Elegant cotton dress',
    colors: ['Blue', 'Green', 'White'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://images.unsplash.com/photo-1572804419140-8f6a3f11c9ff?w=400'],
    stock: 70,
    rating: 4.4,
    reviews: 156,
  },
  {
    name: 'UCB Kids Cardigan',
    brand: 'UCB',
    category: 'Topwear',
    gender: 'Kids',
    mrp: 2000,
    price: 1199,
    discount: 40,
    description: 'Soft cardigan for kids',
    colors: ['Cream', 'Pink', 'Blue'],
    sizes: ['2XS', 'XS', 'S', 'M', 'L'],
    images: ['https://images.unsplash.com/photo-1556821552-5f6abf0c4fa9?w=400'],
    stock: 85,
    rating: 4.4,
    reviews: 123,
  },
];

async function seedProducts() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('MongoDB connected');

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert new products
    const inserted = await Product.insertMany(productsData);
    console.log(`${inserted.length} products inserted successfully!`);

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedProducts();
